var copydir = require('copy-dir');
var fs = require('fs');
copydir.sync('./node_modules/jsonix/jsonschemas', './resources/app/standards/jsonschemas');

//extraction of schema to .json file
//var GHSTSJsonSchema = JSON.parse(fs.readFileSync('./resources/app/standards/01_00_00/GHSTS.jsonschema').toString());
var GHSTS = require('./resources/app/standards/01_00_00/GHSTS').GHSTS;

var count = 0;
var defName_arr = [];

// We reuse GHSTSMappings variable declared in file GHSTSMappings.js which are generated by jsonix
// to count number of GHSTS definitions
GHSTS.typeInfos.forEach(ghstsDefn => {
  defName_arr.push(ghstsDefn.localName);
});

GHSTS.typeInfos.forEach(ghstsDefn => {
  //defName_arr.push(ghstsDefn.localName);
  //console.log(count + ": " + JSON.stringify(ghstsDefn));
  count++;
  var defLocalName = ghstsDefn.localName;
  var jsondef = JSON.stringify(ghstsDefn, undefined, '\t');
  console.log(jsondef);
  var path = './resources/app/standards/01_00_00/jsondefinitions/' + defLocalName + '.json';
  try {
    fs.writeFileSync(path, jsondef);
//    console.log(path + ' was saved!');
  } catch (err) {
    if (err) console.log(path + ' failed as ' + err);
  }
});

var svrs = require('./src/services');
console.log(svrs);
console.log('Done');

