const BACKEND_CONSTANTS = {
  DATA_DIR: 'data',
  PRODUCTS_DIR: 'products',

  APP_LEVEL_SERVICE: 'app',
  DOSSIER_LEVEL_SERVICE: 'dossiers',
  PRODUCT_DOSSIER_FOLDER_CONTACT_SYMBOL: '_##_',
  ACTIVE_SUBMISSION_NAME: 'active',
  LAST_SUBMISSION_NAME: 'last',
  GHSTS_XML_FILENAME: 'ghsts.xml'
};

module.exports = BACKEND_CONSTANTS;